name: 'Validate CloudFormation on PR'

on:
  pull_request:
    types:
      - opened
      - closed
    paths:
      - 'cloudformation/**'

permissions:
  pull-requests: write
  contents: read

jobs:
  validate-cfn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template --template-body file://cloudformation/s3-bucket.yml

      - name: Deploy our stack
        run: |
          stack_name="pr-test-stack-${{ github.event.pull_request.number }}"
          if aws cloudformation describe-stacks --stack-name $stack_name > /dev/null 2>&1; then
            echo "Stack $stack_name already exists. Skipping creation."
          else
            echo "Creating stack: $stack_name"
            aws cloudformation create-stack \
              --stack-name $stack_name \
              --template-body file://cloudformation/s3-bucket.yml \
              --parameters ParameterKey=Environment,ParameterValue=test \
              --capabilities CAPABILITY_NAMED_IAM
          fi
   
      - name: Comment on the PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prNumber = context.payload.pull_request.number;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Cloudformation test stack deployed. Stack name: pr-test-stack-${prNumber}`
            });

  cleanup-on-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Debug Context
        run: echo "${{ toJson(github.event) }}"

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Delete Test Stack
        run: |
          stack_name="pr-test-stack-${{github.event.pull_request.number}}"
          aws cloudformation delete-stack --stack-name $stack_name